import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';

export type Language = 'en' | 'km';

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
};

const en = {
  'nav.home': 'Home',
  'nav.about': 'About',
  'nav.projects': 'Projects',
  'nav.skills': 'Skills',
  'nav.contact': 'Contact',
  'nav.switchLanguage': 'Switch language',
  'home.greeting': "Hi, I'm",
  'home.role': 'Web Developer',
  'home.description': 'Crafting high-performance web applications with precision. I build fast, scalable, and secure full-stack solutions using modern technologies.',
  'home.viewWork': 'View My Work',
  'home.downloadCv': 'Download CV',
  'common.download': 'Download',
  'common.view': 'View',
  'common.pdf': 'PDF',
  'download.aboutTo': 'You are about to download',
  'download.ready': 'Ready to download',
  'download.downloading': 'Downloading',
  'download.preparing': 'Preparing download...',
  'download.complete': 'Download complete',
  'download.cancelled': 'Download cancelled',
  'download.failed': 'Download failed',
  'download.continue': 'Continue Download',
  'download.cancel': 'Cancel',
  'download.cancelDownload': 'Cancel Download',
  'download.tryAgain': 'Try Again',
  'download.back': 'Back',
  'download.close': 'Close',
  'download.return': 'Return to portfolio',
  'download.cvTitle': 'Download CV',
  'download.resumeTitle': 'Download Resume',
  'about.badge': 'Get to know me',
  'about.titleA': 'About',
  'about.titleB': 'Me',
  'about.role': 'Full-Stack Developer',
  'about.available': 'Available for work',
  'about.profileTitle': 'Professional Profile',
  'about.profileText': 'Passionate developer from Cambodia crafting digital experiences with modern web technologies.',
  'about.skillsTitle': 'Technical Skills',
  'about.skillsSubtitle': 'Core Technologies & Expertise',
  'about.frontend': 'Frontend',
  'about.backend': 'Backend',
  'about.database': 'Database',
  'about.experienceTitle': 'Experience',
  'about.experienceText': 'Modern web development stack with 3+ years experience across various projects.',
  'about.achievements': 'Achievements',
  'about.achievementsSubtitle': 'Numbers That Matter',
  'about.projects': 'Projects',
  'about.yearsExp': 'Years Exp.',
  'about.coffees': 'Coffees',
  'about.success': 'Success',
  'about.philosophy': 'Key Philosophy',
  'about.philosophyOne': 'Innovation driven by technical precision.',
  'about.philosophyTwo': 'Continuous shared learning and growth.',
  'about.resume': 'Resume',
  'about.resumeSubtitle': 'Download or View Online',
  'about.coreValues': 'Core Values',
  'about.coreValuesSubtitle': 'Passion, Integrity, Scalability',
  'about.innovation': 'Innovation',
  'about.quality': 'Quality',
  'projects.viewProject': 'View Project',
  'projects.sourceCode': 'Source Code',
  'projects.completed': 'Completed',
  'projects.inProgress': 'In Progress',
  'projects.all': 'All',
  'projects.webApps': 'Web Apps',
  'projects.chatbotAlgorithms': 'Chatbot Algorithms',
  'projects.uxUiDesign': 'UX/UI Design',
  'projects.mobile': 'Mobile',
  'projects.uniqueRing.title': 'Unique Ring',
  'projects.uniqueRing.description': 'The Unique Ring project is a digital service platform designed to verify relationship statuses by linking physical rings to a digital system, helping to reduce deception and confusion regarding romantic statuses. Key Functional Requirements — Verification: provides a trustworthy system to verify if someone is in a relationship. Privacy Control: users can choose between Public (shows partner name and start date) or Private (shows only "Has Partner") modes. Constraints: each person is limited to one registration per lifetime, and all rings require admin activation. Search: allows the public to search for relationship statuses via Name, Ring ID, or Username. System Roles — Visitor: can perform public searches. Registered Couple: can manage their account and relationship privacy. Admin: manages users, approves ring activations, handles relationship records, and ensures data security. Security Measures include password hashing with bcrypt, authentication using JSON Web Tokens (JWT), and data protection via Redis rate limiting for searches and encryption of sensitive data.',
  'projects.weatherDashboard.title': 'Weather Forecast Dashboard',
  'projects.weatherDashboard.description': 'A real-time weather application providing current conditions, multi-day forecasts, and location-based meteorological data, focusing on high-speed data fetching and responsive UI design. Integrates a Weather API (e.g. OpenWeatherMap or WeatherAPI) via asynchronous fetch/axios calls, with dynamic themes that change background colors based on conditions like clear, rainy, or cloudy. Key features include location search (city search or geolocation), display of temperature, humidity, wind speed and weather icons, and error handling for invalid city names or failed API connections.',
  'projects.computerShop.title': 'Computer Shop',
  'projects.computerShop.description': 'A robust object-oriented e-commerce system demonstrating advanced OOP principles, design patterns, and clean architecture. Includes inventory management, payment processing, and comprehensive API integrations.',
  'projects.inventoryManagement.title': 'Inventory Management System',
  'projects.inventoryManagement.description': 'A comprehensive solution designed to streamline stock control, automate order processing, and optimize warehouse efficiency. Features real-time inventory tracking, low-stock alerts, and advanced data reporting to minimize waste and improve business operational accuracy.',
  'projects.ecommerceStorage.title': 'E-commerce Storage',
  'projects.ecommerceStorage.description': 'A robust and scalable backend infrastructure built with the Laravel framework, designed to handle complex business logic, secure API authentication, and efficient database management. This system prioritizes clean code architecture, RESTful API development, and high-performance data processing to support dynamic, data-driven applications.',
  'skills.badge': 'Technical Expertise',
  'skills.title': 'My Skills',
  'skills.description': "A collection of technologies I've mastered to build high-performance, accessible, and beautiful digital experiences.",
  'skills.all': 'All',
  'skills.tools': 'Tools',
  'skills.skills': 'skills',
  'skills.expertise': 'Expertise',
  'skills.cardText': 'Mastering modern web architectural principles to deliver clean and maintainable code bases.',
  'skills.semantic': 'Semantic',
  'skills.accessibility': 'Accessibility',
  'skills.responsive': 'Responsive',
  'skills.animations': 'Animations',
  'skills.relational': 'Relational',
  'skills.optimization': 'Optimization',
  'skills.years3': '3 years exp.',
  'skills.years4': '4 years exp.',
  'skills.years2': '2 years exp.',
  'contact.badge': 'Get In Touch',
  'contact.title': 'Contact Me',
  'contact.description': "Let's discuss your next project and bring your ideas to life.",
  'contact.location': 'Location',
  'contact.viewMap': 'View on Map',
  'contact.email': 'Email',
  'contact.sendEmail': 'Send Email',
  'contact.phone': 'Phone',
  'contact.callNow': 'Call Now',
  'contact.social': 'Social Media',
  'contact.follow': 'Follow my journey',
  'contact.connect': 'Connect',
  'contact.formTitle': 'Send me a message',
  'contact.formSubtitle': "I'll get back to you within 24 hours",
  'contact.fullName': 'Full Name',
  'contact.fullNamePlaceholder': 'Enter your full name',
  'contact.emailAddress': 'Email Address',
  'contact.emailPlaceholder': 'Enter your email address',
  'contact.subject': 'Subject',
  'contact.selectSubject': 'Select a subject',
  'contact.projectInquiry': 'Project Inquiry',
  'contact.collaboration': 'Collaboration',
  'contact.sayingHello': 'Saying Hello',
  'contact.message': 'Message',
  'contact.messagePlaceholder': 'Tell me about your project or how I can help you...',
  'contact.sendMessage': 'Send Message',
  'contact.sending': 'Sending...',
  'contact.sent': 'Email prepared and ready to send.',
  'contact.quickActions': 'Quick Actions',
  'contact.emailMe': 'Email Me',
  'contact.callMe': 'Call Me',
  'contact.scheduleCall': 'Schedule Call',
  'footer.built': 'Built with precision and passion.',
  'footer.privacy': 'Privacy Policy',
} as const;

const km: Record<keyof typeof en, string> = {
  'nav.home': 'ទំព័រដើម',
  'nav.about': 'អំពីខ្ញុំ',
  'nav.projects': 'គម្រោង',
  'nav.skills': 'ជំនាញ',
  'nav.contact': 'ទំនាក់ទំនង',
  'nav.switchLanguage': 'ប្តូរភាសា',
  'home.greeting': 'សួស្តី ខ្ញុំឈ្មោះ',
  'home.role': 'អ្នកអភិវឌ្ឍន៍គេហទំព័រ',
  'home.description': 'ខ្ញុំបង្កើតកម្មវិធីគេហទំព័រដែលលឿន មានសុវត្ថិភាព និងងាយពង្រីក ដោយប្រើបច្ចេកវិទ្យាទំនើប។',
  'home.viewWork': 'មើលគម្រោង',
  'home.downloadCv': 'ទាញយក CV',
  'common.download': 'ទាញយក',
  'common.view': 'មើល',
  'common.pdf': 'PDF',
  'download.aboutTo': 'អ្នកនឹងទាញយក',
  'download.ready': 'រួចរាល់សម្រាប់ទាញយក',
  'download.downloading': 'កំពុងទាញយក',
  'download.preparing': 'កំពុងរៀបចំការទាញយក...',
  'download.complete': 'ទាញយកបានបញ្ចប់',
  'download.cancelled': 'បានបោះបង់ការទាញយក',
  'download.failed': 'ទាញយកបរាជ័យ',
  'download.continue': 'បន្តទាញយក',
  'download.cancel': 'បោះបង់',
  'download.cancelDownload': 'បោះបង់ការទាញយក',
  'download.tryAgain': 'ព្យាយាមម្តងទៀត',
  'download.back': 'ត្រឡប់ក្រោយ',
  'download.close': 'បិទ',
  'download.return': 'ត្រឡប់ទៅ Portfolio',
  'download.cvTitle': 'ទាញយក CV',
  'download.resumeTitle': 'ទាញយកប្រវត្តិរូប',
  'about.badge': 'ស្គាល់ខ្ញុំបន្ថែម',
  'about.titleA': 'អំពី',
  'about.titleB': 'ខ្ញុំ',
  'about.role': 'អ្នកអភិវឌ្ឍន៍ Full-Stack',
  'about.available': 'អាចធ្វើការបាន',
  'about.profileTitle': 'ប្រវត្តិវិជ្ជាជីវៈ',
  'about.profileText': 'អ្នកអភិវឌ្ឍន៍ពីកម្ពុជា ដែលចូលចិត្តបង្កើតបទពិសោធន៍ឌីជីថលដោយបច្ចេកវិទ្យាគេហទំព័រទំនើប។',
  'about.skillsTitle': 'ជំនាញបច្ចេកទេស',
  'about.skillsSubtitle': 'បច្ចេកវិទ្យា និងជំនាញសំខាន់ៗ',
  'about.frontend': 'Frontend',
  'about.backend': 'Backend',
  'about.database': 'Database',
  'about.experienceTitle': 'បទពិសោធន៍',
  'about.experienceText': 'មានបទពិសោធន៍ជាង ៣ ឆ្នាំក្នុងការអភិវឌ្ឍន៍គេហទំព័រទំនើបលើគម្រោងជាច្រើន។',
  'about.achievements': 'សមិទ្ធផល',
  'about.achievementsSubtitle': 'ចំនួនដែលសំខាន់',
  'about.projects': 'គម្រោង',
  'about.yearsExp': 'ឆ្នាំបទពិសោធន៍',
  'about.coffees': 'កាហ្វេ',
  'about.success': 'ជោគជ័យ',
  'about.philosophy': 'គោលការណ៍សំខាន់',
  'about.philosophyOne': 'នវានុវត្តន៍ដែលជំរុញដោយភាពច្បាស់លាស់បច្ចេកទេស។',
  'about.philosophyTwo': 'ការរៀនសូត្រ និងរីកចម្រើនជាបន្តបន្ទាប់។',
  'about.resume': 'ប្រវត្តិរូប',
  'about.resumeSubtitle': 'ទាញយក ឬមើលអនឡាញ',
  'about.coreValues': 'គុណតម្លៃស្នូល',
  'about.coreValuesSubtitle': 'ចំណង់ចំណូលចិត្ត សុចរិតភាព និងភាពងាយពង្រីក',
  'about.innovation': 'នវានុវត្តន៍',
  'about.quality': 'គុណភាព',
  'projects.viewProject': 'មើលគម្រោង',
  'projects.sourceCode': 'កូដប្រភព',
  'projects.completed': 'បានបញ្ចប់',
  'projects.inProgress': 'កំពុងដំណើរការ',
  'projects.all': 'ទាំងអស់',
  'projects.webApps': 'កម្មវិធីគេហទំព័រ',
  'projects.chatbotAlgorithms': 'អាល់ហ្គរីធម៍ Chatbot',
  'projects.uxUiDesign': 'រចនា UX/UI',
  'projects.mobile': 'Mobile',
  'projects.uniqueRing.title': 'Unique Ring',
  'projects.uniqueRing.description': 'គម្រោង Unique Ring គឺជាវេទិកាសេវាឌីជីថលដែលរចនាឡើងសម្រាប់ផ្ទៀងផ្ទាត់ស្ថានភាពទំនាក់ទំនង ដោយភ្ជាប់ចិញ្ចៀនពិតទៅនឹងប្រព័ន្ធឌីជីថល ជួយកាត់បន្ថយការបញ្ឆោត និងភាពច្របូកច្របល់អំពីស្ថានភាពស្នេហា។ តម្រូវការមុខងារសំខាន់ៗ — ការផ្ទៀងផ្ទាត់៖ ផ្តល់ប្រព័ន្ធជឿទុកចិត្តបានសម្រាប់ផ្ទៀងផ្ទាត់ថាតើនរណាម្នាក់កំពុងមានទំនាក់ទំនងឬអត់។ ការគ្រប់គ្រងឯកជនភាព៖ អ្នកប្រើអាចជ្រើសរើសរបៀបសាធារណៈ (បង្ហាញឈ្មោះដៃគូ និងកាលបរិច្ឆេទចាប់ផ្តើម) ឬឯកជន (បង្ហាញតែ "មានដៃគូ")។ កំហិត៖ អ្នកនីមួយៗអាចចុះឈ្មោះបានតែម្តងក្នុងមួយជីវិត ហើយចិញ្ចៀនទាំងអស់ត្រូវការការបើកដំណើរការពីអ្នកគ្រប់គ្រង។ ការស្វែងរក៖ អនុញ្ញាតឲ្យសាធារណជនស្វែងរកស្ថានភាពទំនាក់ទំនងតាមឈ្មោះ លេខសម្គាល់ចិញ្ចៀន ឬឈ្មោះអ្នកប្រើ។ តួនាទីប្រព័ន្ធ — អ្នកទស្សនា៖ អាចធ្វើការស្វែងរកជាសាធារណៈ។ គូស្នេហ៍ដែលបានចុះឈ្មោះ៖ អាចគ្រប់គ្រងគណនី និងឯកជនភាពទំនាក់ទំនងរបស់ខ្លួន។ អ្នកគ្រប់គ្រង៖ គ្រប់គ្រងអ្នកប្រើ អនុម័តការបើកដំណើរការចិញ្ចៀន គ្រប់គ្រងកំណត់ត្រាទំនាក់ទំនង និងធានាសុវត្ថិភាពទិន្នន័យ។ វិធានការសុវត្ថិភាពរួមមានការអ៊ិនគ្រីបពាក្យសម្ងាត់ដោយ bcrypt ការផ្ទៀងផ្ទាត់ដោយប្រើ JSON Web Tokens (JWT) និងការការពារទិន្នន័យតាមរយៈការកំណត់អត្រាស្វែងរកជាមួយ Redis និងការអ៊ិនគ្រីបទិន្នន័យសំខាន់ៗ។',
  'projects.weatherDashboard.title': 'Weather Forecast Dashboard',
  'projects.weatherDashboard.description': 'កម្មវិធីអាកាសធាតុតាមពេលវេលាជាក់ស្តែង ដែលបង្ហាញស្ថានភាពបច្ចុប្បន្ន ការព្យាករណ៍ច្រើនថ្ងៃ និងទិន្នន័យអាកាសធាតុតាមទីតាំង ដោយផ្តោតលើល្បឿនទាញយកទិន្នន័យលឿន និងការរចនាចំណុចប្រទាក់ដែលឆ្លើយតបល្អ។ ភ្ជាប់ជាមួយ Weather API (ដូចជា OpenWeatherMap ឬ WeatherAPI) តាមរយៈការហៅ fetch/axios បែប asynchronous ព្រមទាំងផ្លាស់ប្តូរពណ៌ផ្ទៃខាងក្រោយតាមស្ថានភាពអាកាសធាតុ ដូចជា ថ្ងៃស្រាល ភ្លៀង ឬពពក។ លក្ខណៈពិសេសសំខាន់ៗរួមមានការស្វែងរកទីតាំង (ស្វែងរកទីក្រុង ឬប្រើទីតាំង GPS) ការបង្ហាញសីតុណ្ហភាព សំណើម ល្បឿនខ្យល់ និងរូបតំណាងអាកាសធាតុ ព្រមទាំងការគ្រប់គ្រងកំហុសសម្រាប់ឈ្មោះទីក្រុងមិនត្រឹមត្រូវ ឬការភ្ជាប់ API បរាជ័យ។',
  'projects.computerShop.title': 'Computer Shop',
  'projects.computerShop.description': 'ប្រព័ន្ធពាណិជ្ជកម្មអេឡិចត្រូនិកតាមគោលការណ៍ Object-Oriented ដ៏រឹងមាំ ដែលបង្ហាញពីគោលការណ៍ OOP កម្រិតខ្ពស់ លំនាំរចនា (Design Patterns) និងស្ថាបត្យកម្មកូដស្អាត។ រួមមានការគ្រប់គ្រងស្តុកទំនិញ ដំណើរការទូទាត់ប្រាក់ និងការភ្ជាប់ API ដ៏ទូលំទូលាយ។',
  'projects.inventoryManagement.title': 'Inventory Management System',
  'projects.inventoryManagement.description': 'ដំណោះស្រាយដ៏ទូលំទូលាយដែលរចនាឡើងដើម្បីសម្រួលការគ្រប់គ្រងស្តុក ធ្វើឲ្យដំណើរការបញ្ជាទិញស្វ័យប្រវត្តិ និងបង្កើនប្រសិទ្ធភាពឃ្លាំង។ មានលក្ខណៈពិសេសតាមដានស្តុកតាមពេលវេលាជាក់ស្តែង ការជូនដំណឹងពេលស្តុកជិតអស់ និងរបាយការណ៍ទិន្នន័យកម្រិតខ្ពស់ ដើម្បីកាត់បន្ថយការខាតបង់ និងបង្កើនភាពត្រឹមត្រូវក្នុងប្រតិបត្តិការអាជីវកម្ម។',
  'projects.ecommerceStorage.title': 'E-commerce Storage',
  'projects.ecommerceStorage.description': 'ហេដ្ឋារចនាសម្ព័ន្ធខាងក្រោយដ៏រឹងមាំ និងអាចពង្រីកបាន សាងសង់ដោយប្រើ Laravel framework ដែលរចនាឡើងសម្រាប់ដោះស្រាយតក្កវិជ្ជាអាជីវកម្មស្មុគស្មាញ ការផ្ទៀងផ្ទាត់ API ដោយសុវត្ថិភាព និងការគ្រប់គ្រងមូលដ្ឋានទិន្នន័យប្រកបដោយប្រសិទ្ធភាព។ ប្រព័ន្ធនេះផ្តោតសំខាន់លើស្ថាបត្យកម្មកូដស្អាត ការអភិវឌ្ឍន៍ RESTful API និងដំណើរការទិន្នន័យប្រសិទ្ធភាពខ្ពស់ ដើម្បីគាំទ្រកម្មវិធីដែលដំណើរការដោយទិន្នន័យថាមវន្ត។',
  'skills.badge': 'ជំនាញបច្ចេកទេស',
  'skills.title': 'ជំនាញរបស់ខ្ញុំ',
  'skills.description': 'បច្ចេកវិទ្យាដែលខ្ញុំបានស្ទាត់ជំនាញ ដើម្បីបង្កើតបទពិសោធន៍ឌីជីថលដែលលឿន ងាយប្រើ និងស្រស់ស្អាត។',
  'skills.all': 'ទាំងអស់',
  'skills.tools': 'ឧបករណ៍',
  'skills.skills': 'ជំនាញ',
  'skills.expertise': 'កម្រិតជំនាញ',
  'skills.cardText': 'ស្ទាត់ជំនាញគោលការណ៍ស្ថាបត្យកម្មគេហទំព័រទំនើប ដើម្បីសរសេរកូដស្អាត និងងាយថែទាំ។',
  'skills.semantic': 'Semantic',
  'skills.accessibility': 'Accessibility',
  'skills.responsive': 'Responsive',
  'skills.animations': 'Animations',
  'skills.relational': 'Relational',
  'skills.optimization': 'Optimization',
  'skills.years3': 'បទពិសោធន៍ ៣ ឆ្នាំ',
  'skills.years4': 'បទពិសោធន៍ ៤ ឆ្នាំ',
  'skills.years2': 'បទពិសោធន៍ ២ ឆ្នាំ',
  'contact.badge': 'ទំនាក់ទំនង',
  'contact.title': 'ទាក់ទងខ្ញុំ',
  'contact.description': 'មកពិភាក្សាអំពីគម្រោងបន្ទាប់របស់អ្នក ហើយបង្កើតគំនិតឲ្យក្លាយជាការពិត។',
  'contact.location': 'ទីតាំង',
  'contact.viewMap': 'មើលផែនទី',
  'contact.email': 'អ៊ីមែល',
  'contact.sendEmail': 'ផ្ញើអ៊ីមែល',
  'contact.phone': 'ទូរស័ព្ទ',
  'contact.callNow': 'ហៅឥឡូវ',
  'contact.social': 'បណ្ដាញសង្គម',
  'contact.follow': 'តាមដានដំណើររបស់ខ្ញុំ',
  'contact.connect': 'ភ្ជាប់',
  'contact.formTitle': 'ផ្ញើសារមកខ្ញុំ',
  'contact.formSubtitle': 'ខ្ញុំនឹងឆ្លើយតបក្នុងរយៈពេល ២៤ ម៉ោង',
  'contact.fullName': 'ឈ្មោះពេញ',
  'contact.fullNamePlaceholder': 'បញ្ចូលឈ្មោះពេញរបស់អ្នក',
  'contact.emailAddress': 'អាសយដ្ឋានអ៊ីមែល',
  'contact.emailPlaceholder': 'បញ្ចូលអ៊ីមែលរបស់អ្នក',
  'contact.subject': 'ប្រធានបទ',
  'contact.selectSubject': 'ជ្រើសរើសប្រធានបទ',
  'contact.projectInquiry': 'សំណួរអំពីគម្រោង',
  'contact.collaboration': 'សហការ',
  'contact.sayingHello': 'សួស្តី',
  'contact.message': 'សារ',
  'contact.messagePlaceholder': 'ប្រាប់ខ្ញុំអំពីគម្រោងរបស់អ្នក ឬអ្វីដែលខ្ញុំអាចជួយបាន...',
  'contact.sendMessage': 'ផ្ញើសារ',
  'contact.sending': 'កំពុងផ្ញើ...',
  'contact.sent': 'បានរៀបចំអ៊ីមែលរួចរាល់សម្រាប់ផ្ញើ។',
  'contact.quickActions': 'សកម្មភាពរហ័ស',
  'contact.emailMe': 'អ៊ីមែលមកខ្ញុំ',
  'contact.callMe': 'ហៅខ្ញុំ',
  'contact.scheduleCall': 'កំណត់ពេលហៅ',
  'footer.built': 'បង្កើតឡើងដោយភាពច្បាស់លាស់ និងចំណង់ចំណូលចិត្ត។',
  'footer.privacy': 'គោលការណ៍ឯកជនភាព',
};

const translations: Record<Language, Record<string, string>> = { en, km };

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    if (typeof window === 'undefined') {
      return 'en';
    }

    return localStorage.getItem('language') === 'km' ? 'km' : 'en';
  });

  useEffect(() => {
    document.documentElement.lang = language;
    localStorage.setItem('language', language);
  }, [language]);

  const value = useMemo<LanguageContextValue>(() => ({
    language,
    setLanguage,
    toggleLanguage: () => setLanguage((current) => (current === 'en' ? 'km' : 'en')),
    t: (key) => translations[language][key] ?? translations.en[key] ?? key,
  }), [language]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);

  if (!context) {
    throw new Error('useLanguage must be used inside LanguageProvider');
  }

  return context;
}
