import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';

export type Language = 'en' | 'km';

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
};

const en = {
  'nav.home': 'Home',
  'nav.about': 'About',
  'nav.projects': 'Projects',
  'nav.skills': 'Skills',
  'nav.contact': 'Contact',
  'nav.switchLanguage': 'Switch language',
  'home.greeting': "Hi, I'm",
  'home.role': 'Web Developer',
  'home.description': 'Crafting high-performance web applications with precision. I build fast, scalable, and secure full-stack solutions using modern technologies.',
  'home.viewWork': 'View My Work',
  'home.downloadCv': 'Download CV',
  'common.download': 'Download',
  'common.view': 'View',
  'common.pdf': 'PDF',
  'download.aboutTo': 'You are about to download',
  'download.ready': 'Ready to download',
  'download.downloading': 'Downloading',
  'download.preparing': 'Preparing download...',
  'download.complete': 'Download complete',
  'download.cancelled': 'Download cancelled',
  'download.failed': 'Download failed',
  'download.continue': 'Continue Download',
  'download.cancel': 'Cancel',
  'download.cancelDownload': 'Cancel Download',
  'download.tryAgain': 'Try Again',
  'download.back': 'Back',
  'download.close': 'Close',
  'download.return': 'Return to portfolio',
  'download.cvTitle': 'Download CV',
  'download.resumeTitle': 'Download Resume',
  'about.badge': 'Get to know me',
  'about.titleA': 'About',
  'about.titleB': 'Me',
  'about.role': 'Full-Stack Developer',
  'about.available': 'Available for work',
  'about.profileTitle': 'Professional Profile',
  'about.profileText': 'Passionate developer from Cambodia crafting digital experiences with modern web technologies.',
  'about.skillsTitle': 'Technical Skills',
  'about.skillsSubtitle': 'Core Technologies & Expertise',
  'about.frontend': 'Frontend',
  'about.backend': 'Backend',
  'about.database': 'Database',
  'about.experienceTitle': 'Experience',
  'about.experienceText': 'Modern web development stack with 3+ years experience across various projects.',
  'about.achievements': 'Achievements',
  'about.achievementsSubtitle': 'Numbers That Matter',
  'about.projects': 'Projects',
  'about.yearsExp': 'Years Exp.',
  'about.coffees': 'Coffees',
  'about.success': 'Success',
  'about.philosophy': 'Key Philosophy',
  'about.philosophyOne': 'Innovation driven by technical precision.',
  'about.philosophyTwo': 'Continuous shared learning and growth.',
  'about.resume': 'Resume',
  'about.resumeSubtitle': 'Download or View Online',
  'about.coreValues': 'Core Values',
  'about.coreValuesSubtitle': 'Passion, Integrity, Scalability',
  'about.innovation': 'Innovation',
  'about.quality': 'Quality',
  'projects.viewProject': 'View Project',
  'projects.sourceCode': 'Source Code',
  'projects.completed': 'Completed',
  'projects.inProgress': 'In Progress',
  'projects.all': 'All',
  'projects.webApps': 'Web Apps',
  'projects.chatbotAlgorithms': 'Chatbot Algorithms',
  'projects.uxUiDesign': 'UX/UI Design',
  'projects.mobile': 'Mobile',
  'skills.badge': 'Technical Expertise',
  'skills.title': 'My Skills',
  'skills.description': "A collection of technologies I've mastered to build high-performance, accessible, and beautiful digital experiences.",
  'skills.all': 'All',
  'skills.tools': 'Tools',
  'skills.skills': 'skills',
  'skills.expertise': 'Expertise',
  'skills.cardText': 'Mastering modern web architectural principles to deliver clean and maintainable code bases.',
  'skills.semantic': 'Semantic',
  'skills.accessibility': 'Accessibility',
  'skills.responsive': 'Responsive',
  'skills.animations': 'Animations',
  'skills.relational': 'Relational',
  'skills.optimization': 'Optimization',
  'skills.years3': '3 years exp.',
  'skills.years4': '4 years exp.',
  'skills.years2': '2 years exp.',
  'contact.badge': 'Get In Touch',
  'contact.title': 'Contact Me',
  'contact.description': "Let's discuss your next project and bring your ideas to life.",
  'contact.location': 'Location',
  'contact.viewMap': 'View on Map',
  'contact.email': 'Email',
  'contact.sendEmail': 'Send Email',
  'contact.phone': 'Phone',
  'contact.callNow': 'Call Now',
  'contact.social': 'Social Media',
  'contact.follow': 'Follow my journey',
  'contact.connect': 'Connect',
  'contact.formTitle': 'Send me a message',
  'contact.formSubtitle': "I'll get back to you within 24 hours",
  'contact.fullName': 'Full Name',
  'contact.fullNamePlaceholder': 'Enter your full name',
  'contact.emailAddress': 'Email Address',
  'contact.emailPlaceholder': 'Enter your email address',
  'contact.subject': 'Subject',
  'contact.selectSubject': 'Select a subject',
  'contact.projectInquiry': 'Project Inquiry',
  'contact.collaboration': 'Collaboration',
  'contact.sayingHello': 'Saying Hello',
  'contact.message': 'Message',
  'contact.messagePlaceholder': 'Tell me about your project or how I can help you...',
  'contact.sendMessage': 'Send Message',
  'contact.sending': 'Sending...',
  'contact.sent': 'Email prepared and ready to send.',
  'contact.quickActions': 'Quick Actions',
  'contact.emailMe': 'Email Me',
  'contact.callMe': 'Call Me',
  'contact.scheduleCall': 'Schedule Call',
  'footer.built': 'Built with precision and passion.',
  'footer.privacy': 'Privacy Policy',
} as const;

const km: Record<keyof typeof en, string> = {
  'nav.home': 'ទំព័រដើម',
  'nav.about': 'អំពីខ្ញុំ',
  'nav.projects': 'គម្រោង',
  'nav.skills': 'ជំនាញ',
  'nav.contact': 'ទំនាក់ទំនង',
  'nav.switchLanguage': 'ប្តូរភាសា',
  'home.greeting': 'សួស្តី ខ្ញុំឈ្មោះ',
  'home.role': 'អ្នកអភិវឌ្ឍន៍គេហទំព័រ',
  'home.description': 'ខ្ញុំបង្កើតកម្មវិធីគេហទំព័រដែលលឿន មានសុវត្ថិភាព និងងាយពង្រីក ដោយប្រើបច្ចេកវិទ្យាទំនើប។',
  'home.viewWork': 'មើលគម្រោង',
  'home.downloadCv': 'ទាញយក CV',
  'common.download': 'ទាញយក',
  'common.view': 'មើល',
  'common.pdf': 'PDF',
  'download.aboutTo': 'អ្នកនឹងទាញយក',
  'download.ready': 'រួចរាល់សម្រាប់ទាញយក',
  'download.downloading': 'កំពុងទាញយក',
  'download.preparing': 'កំពុងរៀបចំការទាញយក...',
  'download.complete': 'ទាញយកបានបញ្ចប់',
  'download.cancelled': 'បានបោះបង់ការទាញយក',
  'download.failed': 'ទាញយកបរាជ័យ',
  'download.continue': 'បន្តទាញយក',
  'download.cancel': 'បោះបង់',
  'download.cancelDownload': 'បោះបង់ការទាញយក',
  'download.tryAgain': 'ព្យាយាមម្តងទៀត',
  'download.back': 'ត្រឡប់ក្រោយ',
  'download.close': 'បិទ',
  'download.return': 'ត្រឡប់ទៅ Portfolio',
  'download.cvTitle': 'ទាញយក CV',
  'download.resumeTitle': 'ទាញយកប្រវត្តិរូប',
  'about.badge': 'ស្គាល់ខ្ញុំបន្ថែម',
  'about.titleA': 'អំពី',
  'about.titleB': 'ខ្ញុំ',
  'about.role': 'អ្នកអភិវឌ្ឍន៍ Full-Stack',
  'about.available': 'អាចធ្វើការបាន',
  'about.profileTitle': 'ប្រវត្តិវិជ្ជាជីវៈ',
  'about.profileText': 'អ្នកអភិវឌ្ឍន៍ពីកម្ពុជា ដែលចូលចិត្តបង្កើតបទពិសោធន៍ឌីជីថលដោយបច្ចេកវិទ្យាគេហទំព័រទំនើប។',
  'about.skillsTitle': 'ជំនាញបច្ចេកទេស',
  'about.skillsSubtitle': 'បច្ចេកវិទ្យា និងជំនាញសំខាន់ៗ',
  'about.frontend': 'Frontend',
  'about.backend': 'Backend',
  'about.database': 'Database',
  'about.experienceTitle': 'បទពិសោធន៍',
  'about.experienceText': 'មានបទពិសោធន៍ជាង ៣ ឆ្នាំក្នុងការអភិវឌ្ឍន៍គេហទំព័រទំនើបលើគម្រោងជាច្រើន។',
  'about.achievements': 'សមិទ្ធផល',
  'about.achievementsSubtitle': 'ចំនួនដែលសំខាន់',
  'about.projects': 'គម្រោង',
  'about.yearsExp': 'ឆ្នាំបទពិសោធន៍',
  'about.coffees': 'កាហ្វេ',
  'about.success': 'ជោគជ័យ',
  'about.philosophy': 'គោលការណ៍សំខាន់',
  'about.philosophyOne': 'នវានុវត្តន៍ដែលជំរុញដោយភាពច្បាស់លាស់បច្ចេកទេស។',
  'about.philosophyTwo': 'ការរៀនសូត្រ និងរីកចម្រើនជាបន្តបន្ទាប់។',
  'about.resume': 'ប្រវត្តិរូប',
  'about.resumeSubtitle': 'ទាញយក ឬមើលអនឡាញ',
  'about.coreValues': 'គុណតម្លៃស្នូល',
  'about.coreValuesSubtitle': 'ចំណង់ចំណូលចិត្ត សុចរិតភាព និងភាពងាយពង្រីក',
  'about.innovation': 'នវានុវត្តន៍',
  'about.quality': 'គុណភាព',
  'projects.viewProject': 'មើលគម្រោង',
  'projects.sourceCode': 'កូដប្រភព',
  'projects.completed': 'បានបញ្ចប់',
  'projects.inProgress': 'កំពុងដំណើរការ',
  'projects.all': 'ទាំងអស់',
  'projects.webApps': 'កម្មវិធីគេហទំព័រ',
  'projects.chatbotAlgorithms': 'អាល់ហ្គរីធម៍ Chatbot',
  'projects.uxUiDesign': 'រចនា UX/UI',
  'projects.mobile': 'Mobile',
  'skills.badge': 'ជំនាញបច្ចេកទេស',
  'skills.title': 'ជំនាញរបស់ខ្ញុំ',
  'skills.description': 'បច្ចេកវិទ្យាដែលខ្ញុំបានស្ទាត់ជំនាញ ដើម្បីបង្កើតបទពិសោធន៍ឌីជីថលដែលលឿន ងាយប្រើ និងស្រស់ស្អាត។',
  'skills.all': 'ទាំងអស់',
  'skills.tools': 'ឧបករណ៍',
  'skills.skills': 'ជំនាញ',
  'skills.expertise': 'កម្រិតជំនាញ',
  'skills.cardText': 'ស្ទាត់ជំនាញគោលការណ៍ស្ថាបត្យកម្មគេហទំព័រទំនើប ដើម្បីសរសេរកូដស្អាត និងងាយថែទាំ។',
  'skills.semantic': 'Semantic',
  'skills.accessibility': 'Accessibility',
  'skills.responsive': 'Responsive',
  'skills.animations': 'Animations',
  'skills.relational': 'Relational',
  'skills.optimization': 'Optimization',
  'skills.years3': 'បទពិសោធន៍ ៣ ឆ្នាំ',
  'skills.years4': 'បទពិសោធន៍ ៤ ឆ្នាំ',
  'skills.years2': 'បទពិសោធន៍ ២ ឆ្នាំ',
  'contact.badge': 'ទំនាក់ទំនង',
  'contact.title': 'ទាក់ទងខ្ញុំ',
  'contact.description': 'មកពិភាក្សាអំពីគម្រោងបន្ទាប់របស់អ្នក ហើយបង្កើតគំនិតឲ្យក្លាយជាការពិត។',
  'contact.location': 'ទីតាំង',
  'contact.viewMap': 'មើលផែនទី',
  'contact.email': 'អ៊ីមែល',
  'contact.sendEmail': 'ផ្ញើអ៊ីមែល',
  'contact.phone': 'ទូរស័ព្ទ',
  'contact.callNow': 'ហៅឥឡូវ',
  'contact.social': 'បណ្ដាញសង្គម',
  'contact.follow': 'តាមដានដំណើររបស់ខ្ញុំ',
  'contact.connect': 'ភ្ជាប់',
  'contact.formTitle': 'ផ្ញើសារមកខ្ញុំ',
  'contact.formSubtitle': 'ខ្ញុំនឹងឆ្លើយតបក្នុងរយៈពេល ២៤ ម៉ោង',
  'contact.fullName': 'ឈ្មោះពេញ',
  'contact.fullNamePlaceholder': 'បញ្ចូលឈ្មោះពេញរបស់អ្នក',
  'contact.emailAddress': 'អាសយដ្ឋានអ៊ីមែល',
  'contact.emailPlaceholder': 'បញ្ចូលអ៊ីមែលរបស់អ្នក',
  'contact.subject': 'ប្រធានបទ',
  'contact.selectSubject': 'ជ្រើសរើសប្រធានបទ',
  'contact.projectInquiry': 'សំណួរអំពីគម្រោង',
  'contact.collaboration': 'សហការ',
  'contact.sayingHello': 'សួស្តី',
  'contact.message': 'សារ',
  'contact.messagePlaceholder': 'ប្រាប់ខ្ញុំអំពីគម្រោងរបស់អ្នក ឬអ្វីដែលខ្ញុំអាចជួយបាន...',
  'contact.sendMessage': 'ផ្ញើសារ',
  'contact.sending': 'កំពុងផ្ញើ...',
  'contact.sent': 'បានរៀបចំអ៊ីមែលរួចរាល់សម្រាប់ផ្ញើ។',
  'contact.quickActions': 'សកម្មភាពរហ័ស',
  'contact.emailMe': 'អ៊ីមែលមកខ្ញុំ',
  'contact.callMe': 'ហៅខ្ញុំ',
  'contact.scheduleCall': 'កំណត់ពេលហៅ',
  'footer.built': 'បង្កើតឡើងដោយភាពច្បាស់លាស់ និងចំណង់ចំណូលចិត្ត។',
  'footer.privacy': 'គោលការណ៍ឯកជនភាព',
};

const translations: Record<Language, Record<string, string>> = { en, km };

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    if (typeof window === 'undefined') {
      return 'en';
    }

    return localStorage.getItem('language') === 'km' ? 'km' : 'en';
  });

  useEffect(() => {
    document.documentElement.lang = language;
    localStorage.setItem('language', language);
  }, [language]);

  const value = useMemo<LanguageContextValue>(() => ({
    language,
    setLanguage,
    toggleLanguage: () => setLanguage((current) => (current === 'en' ? 'km' : 'en')),
    t: (key) => translations[language][key] ?? translations.en[key] ?? key,
  }), [language]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);

  if (!context) {
    throw new Error('useLanguage must be used inside LanguageProvider');
  }

  return context;
}
